// src/services/faceService.ts
import axios from "axios";
import FormData from "form-data";

// Point this to your Hugging Face Space URL in production
const PYTHON_API_URL = process.env.FACE_API_URL || "http://127.0.0.1:7860";

export const faceService = {
  /**
   * We keep this method empty so if your server.ts calls
   * faceService.loadModels() on startup, it doesn't crash.
   */
  async loadModels() {
    console.log(
      "Models are now handled externally by the Python AI microservice.",
    );
  },

  /**
   * Send the image buffer to the FastAPI microservice for feature extraction.
   */
  facedetection: async (imageBuffer: Buffer): Promise<number[]> => {
    console.log("FACE: Routing image to AI microservice...");
    console.log("FACE: image size:", imageBuffer.length, "bytes");

    const formData = new FormData();
    formData.append("file", imageBuffer, {
      filename: "capture.jpg",
      contentType: "image/jpeg",
    });

    try {
      const response = await axios.post(
        `${PYTHON_API_URL}/extract-vector`,
        formData,
        {
          headers: {
            ...formData.getHeaders(),
          },
          timeout: 20000, // 20-second timeout
        },
      );

      if (!response.data || !response.data.vector) {
        throw new Error("Invalid response received from AI service.");
      }

      console.log("FACE: Descriptor generated by microservice.");
      console.log("FACE: Descriptor length:", response.data.vector.length);

      return response.data.vector;
    } catch (error: any) {
      console.error("========== FACE AI ERROR ==========");
      if (error.response?.data?.detail) {
        console.error("Detail:", error.response.data.detail);
        throw new Error(error.response.data.detail);
      }
      console.error(error.message);
      console.error("===================================");
      throw new Error(`Face AI service unavailable: ${error.message}`);
    }
  },

  verifyFace: async (
    enrolledface: number[],
    detectedface: number[],
  ): Promise<boolean> => {
    try {
      const response = await axios.post(`${PYTHON_API_URL}/verify-vectors`, {
        enrolled_vector: enrolledface,
        detected_vector: detectedface,
        threshold: 0.55,
      });

      console.log("Face distance:", response.data.distance);
      return response.data.verified;
    } catch (error: any) {
      if (error.response?.data?.detail) {
        throw new Error(error.response.data.detail);
      }
      throw new Error(`Verification service failed: ${error.message}`);
    }
  },
};
